title: Joe`s Blog
author: JoedewYT
email: joeveraart@gmail.com
minima:
  skin: dark
  date_format: "%b %-d, %Y"
description: > # this means to ignore newlines until "baseurl:"
  A blog about all sorts of stuff. from things i experienced to upcoming projects!

# social links
twitter_username: joedewyt # DO NOT include the @ character, or else the build will fail!
github_username:  JoedewYT # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
